const dataCategoryList = {
    categoryList: [
        {
            children: [
                {
                    id: 61,
                    name: 'Drawer Slides',
                    url_key: 'drawer-slides',
                    display_mode: 'PAGE',
                    children: [
                        {
                            id: 62,
                            name: 'Light Duty Slides',
                            url_key: 'light-duty-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 63,
                            name: 'Heavy Duty Slides',
                            url_key: 'heavy-duty-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 64,
                            name: 'Medium Duty Slides',
                            url_key: 'medium-duty-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                    ],
                    __typename: 'CategoryTree',
                },
                {
                    id: 18,
                    name: 'Specialty Slides',
                    url_key: 'specialty-slides',
                    display_mode: 'PAGE',
                    children: [
                        {
                            id: 19,
                            name: 'Linear Track Systems',
                            url_key: 'linear-track-systems',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 37,
                            name: 'Flipper Door Slides',
                            url_key: 'flipper-door-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 39,
                            name: 'Pocket & Bayonet Slides',
                            url_key: 'pocket-bayonet-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 41,
                            name: 'Two-Way Travel Slides',
                            url_key: 'two-way-travel-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 42,
                            name: 'Media Access',
                            url_key: 'media-access',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 43,
                            name: 'Corrosion-Resistant',
                            url_key: 'corrosion-resistant',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 65,
                            name: 'Keyboard Systems',
                            url_key: 'keyboard-systems',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 66,
                            name: 'Tilt Track System',
                            url_key: 'tilt-track-system',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 73,
                            name: 'Electronic Enclosures Slides',
                            url_key: 'electronic-enclosures-slides',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                        {
                            id: 131,
                            name: 'Roller Bearing Slides',
                            url_key: 'roller-bearing',
                            display_mode: 'PRODUCTS',
                            __typename: 'CategoryTree',
                        },
                    ],
                    __typename: 'CategoryTree',
                },
                {
                    id: 13,
                    name: 'Accessories',
                    url_key: 'accessories',
                    display_mode: 'PRODUCTS',
                    children: [],
                    __typename: 'CategoryTree',
                },
                {
                    id: 46,
                    name: 'OEM',
                    url_key: 'oem',
                    display_mode: 'PRODUCTS',
                    children: [],
                    __typename: 'CategoryTree',
                },
                {
                    id: 87,
                    name: 'Shop',
                    url_key: 'shop',
                    display_mode: 'PRODUCTS',
                    children: [],
                    __typename: 'CategoryTree',
                },
            ],
            __typename: 'CategoryTree',
        },
    ],
};

export default dataCategoryList;
